# Generated by Django 2.2 on 2019-04-24 10:42

import StdUML.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrossularStdNamedElement',
            fields=[
                ('grossularstdelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StdUML.GrossularStdElement')),
                ('name', models.TextField(blank=True)),
                ('qualifiedName', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[(StdUML.models.GrossularStdEnmuVisibilityKind('public'), StdUML.models.GrossularStdEnmuVisibilityKind('public')), (StdUML.models.GrossularStdEnmuVisibilityKind('private'), StdUML.models.GrossularStdEnmuVisibilityKind('private')), (StdUML.models.GrossularStdEnmuVisibilityKind('protected'), StdUML.models.GrossularStdEnmuVisibilityKind('protected')), (StdUML.models.GrossularStdEnmuVisibilityKind('package'), StdUML.models.GrossularStdEnmuVisibilityKind('package'))], max_length=20)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('StdUML.grossularstdelement',),
        ),
        migrations.CreateModel(
            name='GrossularStdElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_stduml.grossularstdelement_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='GrossularStdComments',
            fields=[
                ('grossularstdelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StdUML.GrossularStdElement')),
                ('body', models.TextField(blank=True)),
                ('owningElement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownedElement', to='StdUML.GrossularStdElement')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('StdUML.grossularstdelement',),
        ),
        migrations.CreateModel(
            name='GrossularStdNamespaces',
            fields=[
                ('grossularstdnamedelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StdUML.GrossularStdNamedElement')),
                ('memberNamespace', models.ManyToManyField(related_name='ownedMember', to='StdUML.GrossularStdNamedElement')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('StdUML.grossularstdnamedelement',),
        ),
    ]
