# Generated by Django 2.2 on 2019-04-24 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StdUML', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrossularStdPackageableElement',
            fields=[
                ('grossularstdnamedelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StdUML.GrossularStdNamedElement')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('StdUML.grossularstdnamedelement',),
        ),
        migrations.CreateModel(
            name='GrossularStdTypedElement',
            fields=[
                ('grossularstdnamedelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StdUML.GrossularStdNamedElement')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('StdUML.grossularstdnamedelement',),
        ),
        migrations.CreateModel(
            name='GrossularStdType',
            fields=[
                ('grossularstdpackageableelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StdUML.GrossularStdPackageableElement')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('StdUML.grossularstdpackageableelement',),
        ),
    ]
