# Generated by Django 2.2 on 2019-04-24 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StdUML', '0002_grossularstdpackageableelement_grossularstdtype_grossularstdtypedelement'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrossularStdConstraint',
            fields=[
                ('grossularstdpackageableelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StdUML.GrossularStdPackageableElement')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('StdUML.grossularstdpackageableelement',),
        ),
        migrations.CreateModel(
            name='GrossularStdMultiplicityElement',
            fields=[
                ('grossularstdelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StdUML.GrossularStdElement')),
                ('isOrdered', models.BooleanField(default=False)),
                ('isUnique', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('StdUML.grossularstdelement',),
        ),
        migrations.CreateModel(
            name='GrossularStdRelationship',
            fields=[
                ('RelationShipToParent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StdUML.GrossularStdElement')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('StdUML.grossularstdelement',),
        ),
        migrations.RemoveField(
            model_name='grossularstdelement',
            name='id',
        ),
        migrations.AddField(
            model_name='grossularstdelement',
            name='IDElement',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grossularstdpackageableelement',
            name='IDPackageableElement',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grossularstdtypedelement',
            name='type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='typedElement', to='StdUML.GrossularStdType'),
        ),
        migrations.AlterField(
            model_name='grossularstdpackageableelement',
            name='grossularstdnamedelement_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='StdUML.GrossularStdNamedElement'),
        ),
        migrations.CreateModel(
            name='GrossularStdDirectedRelationship',
            fields=[
                ('DirectedRelationShipToParent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='StdUML.GrossularStdRelationship')),
                ('IDDirectedRelationship', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('StdUML.grossularstdrelationship',),
        ),
        migrations.CreateModel(
            name='GrossularStdDependency',
            fields=[
                ('grossularstdpackageableelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='StdUML.GrossularStdPackageableElement')),
                ('grossularstddirectedrelationship_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StdUML.GrossularStdDirectedRelationship')),
                ('supplier', models.ManyToManyField(related_name='supplierDependency', to='StdUML.GrossularStdNamedElement')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('StdUML.grossularstddirectedrelationship', 'StdUML.grossularstdpackageableelement'),
        ),
    ]
