from django.contrib import admin
from CustomUMLClass.models import GrossularCustomUMLClass,GrossularCustomUMLClassMethod,GrossularCustomUMLClassRelationship
from grossular.admin import GrossularAdminSite

# Register your models here.

GrossularAdminSite.register(GrossularCustomUMLClass)
GrossularAdminSite.register(GrossularCustomUMLClassMethod)
GrossularAdminSite.register(GrossularCustomUMLClassRelationship)