from django.contrib import admin
from grossular.admin import GrossularAdminSite
from CustomUMLComponent.models import GrossularCustomUMLComponent, GrossularCustomUMLComponentInterface, \
    GrossularCustomUMLComponentPackage, GrossularCustomUMLComponentRelationship

# Register your models here.


GrossularAdminSite.register(GrossularCustomUMLComponentPackage)
GrossularAdminSite.register(GrossularCustomUMLComponentRelationship)
GrossularAdminSite.register(GrossularCustomUMLComponent)
GrossularAdminSite.register(GrossularCustomUMLComponentInterface)
